### ISSUE TITLE
Posts Share Bar add vk.com

### ISSUE THREAD

**Issue by AppoPro** [presscustomizr/hueman-addons#10]
Hello, if possible can please add social network [vk.com](http://vk.com/) thanks.

**Comment by Nikeo** [comment]
Hi, the javascript plugin used in the plugin does not support vk.
However, you can use a specific plugin to add vk.com : https://wordpress.org/support/topic/share-buttons-how-to-add-vkcom-to-it?replies=5

Hope this helps !
