### ISSUE TITLE
Share bar blocking view in mobile

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/hueman-addons#11]
Hi,

As reported by user.
https://wordpress.org/support/topic/featured-posts-still-appearing-in-list-and-sticky-social-bar-in-mobile

The sticky share bar is blocking view on mobile.

This is a screenshot I took on my iPhone.
http://i.imgur.com/KkorYNn.png

Thank you
Denzel

**Comment by denzelchia** [comment]
Hi Nicolas,

Thank you!
Sorry for reporting in wrong repository. :)

Regards,
Denzel
