### ISSUE TITLE
Disable Sharebar "Sticky" Position on Tablet

### ISSUE THREAD

**Issue by robbinhood** [presscustomizr/hueman-addons#15]
If "Make the Share Bar sticky" option is enabled, sharebar scrolls on top of post content. Disable "sticky" positioning on tablets.

Additional report: https://wordpress.org/support/topic/share-buttons-not-shown-on-mobile/

**Comment by robbinhood** [comment]
Also applies to mobile phones in landscape mode:
https://wordpress.org/support/topic/hueman-shortcodes-sharebar-problem

**Comment by Nikeo** [comment]
ok. thanks for reporting the problem @robbinhood
