### ISSUE TITLE
Allow Custom Links on Sharebar

### ISSUE THREAD

**Issue by robbinhood** [presscustomizr/hueman-addons#17]
https://wordpress.org/support/topic/sharebar-issue-development

**Comment by marthen** [comment]
Hi, I can see only '+' and twitter icons in the share toolbar. Non of them even work. How do I fix the share toolbar? I have selected all social media in share settings.

Thanks
![screen shot 2016-06-21 at 11 56 17](https://cloud.githubusercontent.com/assets/1841354/16225519/3ec33250-37a7-11e6-8fed-cffa126dc573.png)


Martin
