### ISSUE TITLE
Problem with Sharebar

### ISSUE THREAD

**Issue by ju2x** [presscustomizr/hueman-addons#18]
Hello,

I have a problem with the sharebar inside the articles, it's don't works, only twitter logo with # as link.

http://www.simplecommegeek.net

Thanks
JU2x

however this theme is great, thanks a lot ;-)

**Comment by robbinhood** [comment]
@ju2x - Please post your issue on the theme support forum so we can take a look at it:
https://wordpress.org/support/theme/hueman#postform
Thanks.
