### ISSUE TITLE
I am unable to get the option hide caption= details

### ISSUE THREAD

**Issue by subhakantak** [presscustomizr/hueman-addons#19]
Hi Team,

Whenever i am sharing my post it includes a caption=  some number**. Please see the picture where i marked the particular details highlighted in yellow.
I really do not want want to see it as it is not looking aesthetic.Please help as how i can hide it.

![image](https://cloud.githubusercontent.com/assets/20593067/17049820/1d07bebe-500d-11e6-9014-d3756351bc03.png)

I will be really appreciate if someone help me removing or hiding this details without removing the picture.

**Comment by robbinhood** [comment]
@subhakantak - please post a topic in the theme support forum so we can take a look at the issue. Thanks. https://wordpress.org/support/theme/hueman#postform
