### ISSUE TITLE
Skopified layout - question

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/hueman-addons#28]
0) Layouts skopified  (boolean flags hu_layout_option_skopified specific per content post meta created )
1) Disable hueman addons
2) change specific page layout value (via edit page)
3) activate hueman addons

=> the current layout skopifier code doesn't take care of the new value as per hu_layout_option_skopified specific per content post meta created

**Comment by Nikeo** [comment]
ok.
A work around would be to delete the skopified booleans from db on deactivation then.
