### ISSUE TITLE
[enhancement] Add shortcode for flexslider/"featured posts" slider

### ISSUE THREAD

**Issue by fwolfst** [presscustomizr/hueman-addons#33]
It would be great if the theme/the addon-plugin would add shortcode support to display the flexslider/featured posts-slider.

**Comment by fwolfst** [comment]
It basically would need this code

```
+ function hueman_addon_shortcode_featured_flexslider() {
+   ob_start();
+   get_template_part('parts/featured_custom');
+   $ret = ob_get_contents();
+   ob_end_clean();
+   return $ret;
+ }
+ 
+ add_shortcode( 'ha_featured_news', 'hueman_addon_shortcode_featured_flexslider' );
```

Plus the hard(er) part: figuring out how to load the `flexslider.min.js` asset on the right pages.

**Comment by ghost** [comment]
yes loading the flexslider when the shortcode is embedded is the complex part.
A possible solution would be to pre process the post content in a is_singular() context, and detect if the shortcode is embedded.

I'm currently working a simple content builder to embed content blocks like this, and others like custom post grids, html content, etc... . It will be available on home page for the Hueman Addons and in every contexts in Hueman Pro.
