### ISSUE TITLE
Incompatibility to polylang plugin (somehow seems to interfere with menu switching)

### ISSUE THREAD

**Issue by fwolfst** [presscustomizr/hueman-addons#34]
As pointed out it https://github.com/presscustomizr/hueman/issues/377 it seems that at least the topbar menu will not chose to the right languages menu if hueman addons are activated. For me it would be fine if the menu options were not to be edited on a per-"view" base.

**Comment by fwolfst** [comment]
Any chance that this gets fixed in the next release? Considering a fork that removes the per-view-menubar definition (from my quick scans this seems to be the most likely place where the bug/incompatibility could be found).

**Comment by fwolfst** [comment]
Editing `./addons/skop/czr-skop.php` and removing `'nav_menu_locations'` the two lines (https://github.com/presscustomizr/hueman-addons/blob/master/addons/skop/czr-skop.php#L190, https://github.com/presscustomizr/hueman-addons/blob/master/addons/skop/czr-skop.php#L268) solves this issue.
Of course menu positions can then not be modified in the customizr-sense anymore, but at least you can use the addon for multilingual sites (with polylang) again.

**Comment by ghost** [comment]
Thank you very much for this analysis.

Can you confirm that, apart from the nav menus, you don't have other particular compatibility issues between Polylang and the Hueman Addons ?

**Comment by fwolfst** [comment]
Sorry @nikeo I cannot really jugde this yet, but until now nothing
jumped to my eye, seems to work fine on first sight.

**Comment by ghost** [comment]
ok. for me too, but a second opinion is always better.

A possible solution will be to add an option to reduce the customization capabilities ( the per page customization ) for the navigation menu. This will be typically useful to fix the compatibility issue with polylang.

**Comment by skenune** [comment]
Same problem with me. I tried succesfully the solution of @fwolfst. Works fine to select the appropriate language, even with several languages.
But then the new problem appears: affecting a specific menu for a single page is not working anymore. The automatic preview works fine but after saving the specific menu disappears.
I can't figure out which one is responsible: polylang or hueman addon or both of them used simultaneously.

**Comment by skenune** [comment]
To go further, I uninstalled polylang and tried WPML. Everything works perfect and @fwolfst solution is no more needed.
So the problem really seems to be an uncompatibility between polylang and hueman addon.

**Comment by Birnou** [comment]
@skenune , so does this mean that there wont be any way to use Polylang , except if one use the solution of @fwolfst ?
so if we uninstall Polylang, does all the settings lost if moving to WPML...
@Nikeo any chance to nativaly update the hueman theme with the @fwolfst solution ?
thanks all
