### ISSUE TITLE
Share Bar not showing!

### ISSUE THREAD

**Issue by lizaguiar** [presscustomizr/hueman-addons#4]
I´ve just updated my old Hueman version (made by Alx) to the new v. 3.1.0 one, from Presscustomizr. Had to install hueman-addons to get Dropcap, Hr and Share Bar functionalities.

But, **Share Bar is just not showing up at all!** Despite being the plugin "Hueman Addons" **Activated** and being checked both "Single Post Share Bar" and "Make the Share Bar Sticky" under Theme Options > Social Links.

Is there another thing that i must do to make Share Bar available? **Any other option somewhere that I have to check**?

As you can see below, "hr" functionality is fine. But where is the Share Bar? Take a look:
http://carteirarica.com.br/gastar-dinheiro-maneira-ridicula/

==============================
Source shows it loads Sharrre javascript file:
`<script type='text/javascript' src='//carteirarica.com.br/wp-content/plugins/hueman-addons/assets/front/js/jQuerySharrre.min.js?ver=4.5'></script>
`

But the Html and the inline javascript **ARE NOT** in the output:

Html doesn´t have: 
`<div class="sharrre-container"> ... </div>`

Neither the scripts:
```
<script type="text/javascript">
	// Sharrre
	jQuery(document).ready(function(){
		jQuery('#twitter').sharrre({
(...)</script>
```

**Comment by denzelchia** [comment]
Hi Lizaguiar,

Please purge your W3 Total Cache's cache content.

I am seeing two child theme stylesheet link in your page source, this is a hint that your cache is not properly updated.

Thank you.
