### ISSUE TITLE
Fix : Fatal error: Class ‘HA_Customize_Header_Image_Data_Setting’ not found

### ISSUE THREAD

**Issue by ghost** [presscustomizr/hueman-addons#42]
https://wordpress.org/support/topic/fatal-error-class-ha_customize_header_image_data_setting-not-found/#post-9516124

> I recently installed the Hueman theme and now when I try to preview any other theme I get this message:
> Fatal error: Class ‘HA_Customize_Header_Image_Data_Setting’ not found in /home/simplemg/public_html/wp-content/plugins/hueman-addons/addons/skop/czr-skop.php on line 2333
> I do not know what to do and I want to change to another theme. Please help.
> 
> Thank yoy

**Comment by eri-trabiccolo** [comment]
see also:
https://github.com/presscustomizr/hueman-pro-addons/issues/104

**Comment by ghost** [comment]
Ah that's it, I remember it was reported already, thanks
