### ISSUE TITLE
Hueman Addons : Multisite compatibility problem

### ISSUE THREAD

**Issue by ghost** [presscustomizr/hueman-addons#43]
https://secure.helpscout.net/conversation/447461231/33223/

> To a logged in user, It seems to mess up what is displayed in the admin menu, and title of the site. The site when logged in will change the title of the site to "Network Name" and change the name of each site in the admin menu/network menu for "My Sites" to display the "Network Name"
> 
> While logged out, it displays just fine.
> 
> You can view the error here. https://turnergames.net/files/images/theme_error.png

> 
Yeah, I tested and retested just now. It's fine with Twenty Seventeen default theme. No errors. But I have narrowed down the issue, to not the theme, but the "Hueman Addons" plugin. When deactivated it displays correctly, so for the time being I disabled the plugin.

**Comment by eri-trabiccolo** [comment]
Ah we never opened this issue then?!
We have various reports about this bug...

**Comment by eri-trabiccolo** [comment]
Ah sorry, we did, in hueman
https://github.com/presscustomizr/hueman/issues/561
and hueman-pro-addons
https://github.com/presscustomizr/hueman-pro-addons/issues/97

**Comment by ghost** [comment]
yes I also was surprised to not find it here.
I did not check on hueman tough

**Comment by ghost** [comment]
ah here they are OK thx

**Comment by eri-trabiccolo** [comment]
Because in hueman-pro-addons I mispelled multisite in the issue title. Corrected now :(

**Comment by ghost** [comment]
also reported here 
https://wordpress.org/support/topic/bad-bug/#post-9968357

**Comment by ghost** [comment]
and here : https://wordpress.org/support/topic/multisite-title-problem-still-not-resolved/

**Comment by eri-trabiccolo** [comment]
see:
https://github.com/presscustomizr/skope/pull/8
