### ISSUE TITLE
2.0.16 + Child Theme = Notices on every page

### ISSUE THREAD

**Issue by cprivitere** [presscustomizr/hueman-addons#47]
After upgrading to 2.0.16 of the hueman-addons we see the following on the top of every page when we use our child theme that's based on Hueman:
```
Notice: Use of undefined constant TEMPLATEPATH - assumed 'TEMPLATEPATH' in /var/www/web/wp-includes/theme.php on line 136

Notice: Use of undefined constant STYLESHEETPATH - assumed 'STYLESHEETPATH' in /var/www/web/wp-includes/theme.php on line 136

Notice: Use of undefined constant TEMPLATEPATH - assumed 'TEMPLATEPATH' in /var/www/web/wp-includes/theme.php on line 136

Notice: Use of undefined constant STYLESHEETPATH - assumed 'STYLESHEETPATH' in /var/www/web/wp-includes/theme.php on line 136
```
Rolling back to 2.0.15 removes the notices. Using Hueman directly also removes the notices. Something about the latest plugin version and child themes isn't quite working right.

**Comment by signaleleven** [comment]
Was https://github.com/presscustomizr/hueman-addons/issues/46 closed in favor of this?
