### ISSUE TITLE
PC_AC_VERSION const not defined

### ISSUE THREAD

**Issue by sgomez** [presscustomizr/hueman-addons#49]
PC_AC_VERSION is not defined in [ccat-contextualizer.php](https://github.com/presscustomizr/hueman-addons/blob/dev/contextualizer/ccat-contextualizer.php#L1371).

This error is showed in dev environment:

```
<b>Warning</b>:  Use of undefined constant PC_AC_VERSION - assumed 'PC_AC_VERSION' (this will throw an Error in a future version of PHP) in <b>/var/www/html/wp-content/plugins/hueman-addons/contextualizer/ccat-contextualizer.php</b> on line <b>1371</b><br />
```

**Comment by ghost** [comment]
Thanks for reporting.
We'll fix the issue for the next release
