### ISSUE TITLE
Print the already loaded  error_logs for skope and czr_base_fmk only if NIMBLE_DEV or CZR_DEV 

### ISSUE THREAD

**Issue by ghost** [presscustomizr/hueman-addons#50]
- "The czr_base_fmk has already been loaded"
- The skope has already been loaded

**Comment by cengizhan** [comment]
i have a huge php log with these messages. anybody knows how to disable this message?

**Comment by ghost** [comment]
@cengizhan a fix is on the way. Thanks for reporting your issue.
