### ISSUE TITLE
disabled social share buttons : there is still block area stolen from the content

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/hueman-addons#6]
>  I noticed one bug, though. I have disabled social share buttons, but there is still block area stolen from the content :(

![original](https://cloud.githubusercontent.com/assets/3038156/14641131/0ce93b46-0645-11e6-9ff6-f6aeb26974a1.jpg)

**Comment by robbinhood** [comment]
Sane as issue #5

**Comment by robbinhood** [comment]
Also https://github.com/presscustomizr/hueman/issues/234
